/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#e1e2e5",
        "surface-tint": "#f2bd79",
        "surface-container-lowest": "#0b0f11",
        "on-tertiary-fixed": "#161c1f",
        "surface-variant": "#323537",
        "on-background": "#e1e2e5",
        "secondary-fixed": "#ffddaf",
        "secondary-container": "#5e410f",
        "on-surface": "#e1e2e5",
        "secondary": "#e9c082",
        "inverse-primary": "#7e561c",
        "tertiary-container": "#8e9497",
        "outline": "#9c8e80",
        "on-tertiary-fixed-variant": "#42484a",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#272d2f",
        "on-secondary": "#432c00",
        "error": "#ffb4ab",
        "on-secondary-container": "#d7af73",
        "on-error": "#690005",
        "primary": "#b98a4b", 
        "on-primary": "#111416",
        "surface-bright": "#373a3c",
        "primary-fixed-dim": "#f2bd79",
        "surface-container-low": "#11171B", 
        "on-primary-fixed": "#2a1800",
        "tertiary": "#c1c7ca",
        "tertiary-fixed": "#dee3e6",
        "surface-container": "#1d2022",
        "tertiary-fixed-dim": "#c1c7ca",
        "on-primary-container": "#3f2600",
        "surface-container-highest": "#323537",
        "outline-variant": "#4f4539",
        "primary-container": "#b98a4b",
        "error-container": "#93000a",
        "background": "#080B0D", 
        "on-secondary-fixed": "#281800",
        "on-surface-variant": "#d3c4b4",
        "surface-container-high": "#272a2d",
        "inverse-on-surface": "#2e3133",
        "surface-dim": "#111416",
        "on-secondary-fixed-variant": "#5e410f",
        "primary-fixed": "#ffddb5",
        "on-primary-fixed-variant": "#633f04",
        "surface": "#11171B", 
        "on-tertiary": "#2b3134",
        "secondary-fixed-dim": "#e9c082"
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem"
      },
      spacing: {
        "margin-desktop": "80px",
        "section-gap": "120px",
        "unit": "4px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "container-max": "1440px"
      },
      fontFamily: {
        "body-lg": ["Manrope"],
        "label-caps": ["Manrope"],
        "body-md": ["Manrope"],
        "headline-lg": ["Manrope"],
        "display-lg": ["Manrope"],
        "headline-xl": ["Manrope"],
        "headline-lg-mobile": ["Manrope"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", letterSpacing: "0.01em", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1", letterSpacing: "0.15em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-xl": ["48px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg-mobile": ["28px", { lineHeight: "1.3", fontWeight: "700" }]
      }
    },
  },
  plugins: [],
}
